# ---------------------------------------------------------------------------------------------------
# Copyright (c) 2026 by Oliver Bründler
# Authors: Oliver Bruendler
# ---------------------------------------------------------------------------------------------------

# ---------------------------------------------------------------------------------------------------
# Description
# ---------------------------------------------------------------------------------------------------
# Sample linear approximations used to verify that the Python model (olo_fix_lin_approx) and the
# generated HDL are bit-true. The samples cover all combinations of signed/unsigned input and
# signed/unsigned output.
#
# The entities and testbenches are generated by sim/codegen.py before VUnit detects the files.

# ---------------------------------------------------------------------------------------------------
# Imports
# ---------------------------------------------------------------------------------------------------
import sys
import os
import shutil
import numpy as np

# Import olo_fix
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "../../../src/fix/python")))
from olo_fix import olo_fix_lin_approx, olo_fix_lin_approx_cfg
from en_cl_fix_pkg import *

# ---------------------------------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------------------------------
# Directory the generated code and the co-simulation files are written to
GENERATED_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), "generated"))

# Number of samples simulated per approximation
SIM_POINTS = 1000

# Sample approximations - one per signedness combination of input/output
SAMPLES = {
    # unsigned input -> unsigned output
    "sqrt_u2u": olo_fix_lin_approx_cfg(
        function=lambda x: np.sqrt(x),
        in_fmt=FixFormat(0, 0, 16),
        out_fmt=FixFormat(0, 0, 16),
        offs_fmt=FixFormat(0, 0, 18),
        grad_fmt=FixFormat(0, 4, 10),
        points=256,
        name="sqrt_u2u",
        valid_range=(0.25, 1.0)),
    # unsigned input -> signed output
    "sin_u2s": olo_fix_lin_approx_cfg(
        function=lambda x: np.sin(x*2*np.pi)*(1 - 2**-16),
        in_fmt=FixFormat(0, 0, 16),
        out_fmt=FixFormat(1, 0, 16),
        offs_fmt=FixFormat(1, 0, 18),
        grad_fmt=FixFormat(1, 3, 12),
        points=256,
        name="sin_u2s"),
    # signed input -> signed output
    "tanh_s2s": olo_fix_lin_approx_cfg(
        function=lambda x: np.tanh(3*x),
        in_fmt=FixFormat(1, 0, 16),
        out_fmt=FixFormat(1, 0, 16),
        offs_fmt=FixFormat(1, 0, 18),
        grad_fmt=FixFormat(0, 2, 12),
        points=256,
        name="tanh_s2s"),
    # signed input -> unsigned output (truncation instead of rounding)
    "square_s2u": olo_fix_lin_approx_cfg(
        function=lambda x: x**2*(1 - 2**-16),
        in_fmt=FixFormat(1, 0, 16),
        out_fmt=FixFormat(0, 0, 16),
        offs_fmt=FixFormat(0, 0, 18),
        grad_fmt=FixFormat(1, 1, 12),
        points=256,
        name="square_s2u",
        round=FixRound.Trunc_s,
        saturate=FixSaturate.Sat_s),
}

# ---------------------------------------------------------------------------------------------------
# Functionality
# ---------------------------------------------------------------------------------------------------
def generate():
    """
    Generate the VHDL entities, the testbenches and the co-simulation files for all samples
    """
    # Start from a clean directory to avoid stale files from renamed samples
    shutil.rmtree(GENERATED_DIR, ignore_errors=True)
    os.makedirs(GENERATED_DIR)

    for cfg in SAMPLES.values():
        approx = olo_fix_lin_approx(cfg)
        approx.generate_entity(GENERATED_DIR, olo_library="olo")
        approx.generate_tb(GENERATED_DIR, olo_library="olo", sim_points=SIM_POINTS)

if __name__ == "__main__":
    generate()
