# File names are either absolute or relative to the parent folder of the
# vhdl_ls.toml file and supports glob-style patterns.

[libraries]

# olo
olo.files = [
  'src/base/vhdl/*.vhd',
  'src/axi/vhdl/*.vhd',
  'src/intf/vhdl/*.vhd'
]

# vunit related libraries (depend on your installation location of vunit)
vunit_lib.files = [
  '.venv/lib/python3.13/site-packages/vunit/**/*.vhd'
]

# test
olo_tb.files = [
  'test/*/*/*.vhd',
  'test/tb/*.vhd',
]