---------------------------------------------------------------------------------------------------
-- Copyright (c) 2026 by Oliver Bründler
-- All rights reserved.
-- Authors: Oliver Bruendler
---------------------------------------------------------------------------------------------------

---------------------------------------------------------------------------------------------------
-- Description
---------------------------------------------------------------------------------------------------
-- This entity approximates sine and cosine of one quadrant. The input is a phase in rotations
-- covering one quadrant, i.e. the range [0, 0.25), which corresponds to 0 to 90 degrees. The input
-- format therefore must be (0, -2, N).
--
-- Only the sine is stored in a table. The cosine is read from the same table through a second read
-- port using the mirrored address 0.25-t, because cos(2*pi*t) = sin(2*pi*(0.25-t)).
--
-- The tables are optimized for every supported output format and they are contained in
-- olo_fix_private_lin_approx_qsin_pkg, which is generated by the Python model.
--
-- Use olo_fix_sin to calculate sine and cosine over all four quadrants.
--
-- Documentation:
-- https://github.com/open-logic/open-logic/blob/main/doc/fix/olo_fix_lin_approx_qsin.md
--
-- Note: The link points to the documentation of the latest release. If you
--       use an older version, the documentation might not match the code.

---------------------------------------------------------------------------------------------------
-- Libraries
---------------------------------------------------------------------------------------------------
library ieee;
    use ieee.std_logic_1164.all;
    use ieee.numeric_std.all;

library work;
    use work.olo_base_pkg_math.all;
    use work.olo_base_pkg_string.all;
    use work.olo_base_pkg_attribute.all;
    use work.en_cl_fix_pkg.all;
    use work.olo_fix_pkg.all;
    use work.olo_fix_private_lin_approx_qsin_pkg.all;

---------------------------------------------------------------------------------------------------
-- Entity Declaration
---------------------------------------------------------------------------------------------------

entity olo_fix_lin_approx_qsin is
    generic (
        -- Formats
        OutFmt_g    : string  := "(1, 0, 16)";
        InFmt_g     : string  := "(0, -2, 20)";
        -- Configuration
        CosOutput_g : boolean := false;
        MemStyle_g  : string  := "auto";
        -- Round / Saturate
        Round_g     : string  := FixRound_NonSymPos_c;
        Saturate_g  : string  := FixSaturate_Sat_c
    );
    port (
        -- Control Ports
        Clk       : in    std_logic;
        Rst       : in    std_logic;
        -- Input
        In_Valid  : in    std_logic := '1';
        In_Data   : in    std_logic_vector(fixFmtWidthFromString(InFmt_g) - 1 downto 0);
        -- Output
        Out_Valid : out   std_logic;
        Out_Sin   : out   std_logic_vector(fixFmtWidthFromString(OutFmt_g) - 1 downto 0);
        Out_Cos   : out   std_logic_vector(fixFmtWidthFromString(OutFmt_g) - 1 downto 0)
    );
end entity;

architecture rtl of olo_fix_lin_approx_qsin is

    -- Constants
    constant EntityName_c : string      := "olo_fix_lin_approx_qsin";
    constant InFmt_c      : FixFormat_t := cl_fix_format_from_string(InFmt_g);
    constant OutFmt_c     : FixFormat_t := cl_fix_format_from_string(OutFmt_g);

    -- Table configuration. The table is selected by name from the generated package - the same name
    -- is assembled by the Python model (see qsin_table_name()).
    constant TableName_c : string := "qsin_i" & integer'image(OutFmt_c.I) &
                                     "f" & integer'image(OutFmt_c.F);

    constant Table_c    : LinApproxTable_t := getTable(TableName_c);
    constant Points_c   : positive         := getTableSize(TableName_c);
    constant OffsFmt_c  : string           := getOffsetFmt(TableName_c);
    constant GradFmt_c  : string           := getGradientFmt(TableName_c);
    constant TblWidth_c : positive         := fixFmtWidthFromString(OffsFmt_c) +
                                              fixFmtWidthFromString(GradFmt_c);

    -- Recommended minimum input resolution. Over one quadrant the sine changes by one, hence two
    -- bits of margin keep the phase quantization below half an LSB of the output. Below this
    -- resolution the entity still works, but the accuracy is limited by the phase and not by the
    -- table.
    constant MinInBits_c : positive := OutFmt_c.F + 2;

    -- Latency of olo_fix_lin_approx_calc. The zero flag is delayed by the same number of stages.
    constant CalcLatency_c : positive := 8;

    -- Peak value of the wave. Without integer bit the wave is scaled to 1.0-1LSB, hence the peak is
    -- the largest representable value. With integer bit the wave is unscaled.
    function peakValue return std_logic_vector is
    begin
        if OutFmt_c.I = 0 then
            return cl_fix_max_value(OutFmt_c);
        end if;
        return cl_fix_from_real(1.0, OutFmt_c);
    end function;

    constant Peak_c : std_logic_vector(cl_fix_width(OutFmt_c) - 1 downto 0) := peakValue;
    constant Zero_c : std_logic_vector(cl_fix_width(OutFmt_c) - 1 downto 0) := (others => '0');

    -- Table types
    subtype TblEntry_t is std_logic_vector(TblWidth_c - 1 downto 0);
    type Tbl_t is array (0 to Points_c - 1) of TblEntry_t;

    -- Strip the padding the generated package uses to give all tables the same entry width
    function tableContent return Tbl_t is
        variable Tbl_v : Tbl_t;
    begin

        for i in Tbl_v'range loop
            Tbl_v(i) := Table_c(i)(TblWidth_c - 1 downto 0);
        end loop;

        return Tbl_v;
    end function;

    -- Table content - each entry contains the gradient (MSBs) and the offset (LSBs)
    -- Implemented as shared variable because attributes do not apply properly to constants
    shared variable Table_v : Tbl_t := tableContent;

    -- Synthesis attributes - control ROM style
    attribute rom_style of Table_v    : variable is MemStyle_g;
    attribute romstyle of Table_v     : variable is MemStyle_g;
    attribute syn_romstyle of Table_v : variable is MemStyle_g;

    -- Two Process Method
    type TwoProcess_r is record
        -- Zero flag, delayed to arrive at the output stage together with the calculation result
        ZeroPipe  : std_logic_vector(0 to CalcLatency_c - 1);
        Out_Valid : std_logic;
        Out_Sin   : std_logic_vector(Out_Sin'range);
        Out_Cos   : std_logic_vector(Out_Cos'range);
    end record;

    signal r, r_next : TwoProcess_r;

    -- Signals
    signal MirrorData : std_logic_vector(In_Data'range);
    signal SinAddr    : std_logic_vector(log2ceil(Points_c) - 1 downto 0);
    signal SinData    : TblEntry_t;
    signal SinResult  : std_logic_vector(Out_Sin'range);
    signal SinValid   : std_logic;
    signal CosAddr    : std_logic_vector(log2ceil(Points_c) - 1 downto 0);
    signal CosData    : TblEntry_t;
    signal CosResult  : std_logic_vector(Out_Cos'range);

begin

    -- *** Assertions ***
    -- synthesis translate_off
    assert OutFmt_c.S = 1
        report errorMessage(EntityName_c, "OutFmt_g must be signed")
        severity error;
    assert InFmt_c.S = 0 and InFmt_c.I = -2
        report errorMessage(EntityName_c, "InFmt_g must be (0, -2, N) - the quarter phase covers " &
               "one quadrant only, i.e. the range [0, 0.25) in rotations")
        severity error;
    assert cl_fix_width(InFmt_c) > log2ceil(Points_c)
        report errorMessage(EntityName_c, "InFmt_g must be wider than the table has index bits")
        severity error;
    assert cl_fix_width(InFmt_c) >= MinInBits_c
        report errorMessage(EntityName_c, "InFmt_g resolution limits the accuracy - at least " &
               integer'image(MinInBits_c) & " bits are recommended for OutFmt_g " & OutFmt_g)
        severity warning;
    -- synthesis translate_on

    -- *** Mirrored Address ***
    -- The two's complement of the quarter phase is exactly 1-a for every a /= 0. The a = 0 case is
    -- handled by the zero flag in the output stage.
    MirrorData <= std_logic_vector(0 - unsigned(In_Data));

    -- *** Table (ROM, one cycle read latency) ***
    p_table_sin : process (Clk) is
    begin
        if rising_edge(Clk) then
            SinData <= Table_v(to_integer(unsigned(SinAddr)));
        end if;
    end process;

    -- *** Combinatorial Process ***
    p_comb : process (all) is
        variable v : TwoProcess_r;
    begin
        -- *** Hold variables stable ***
        v := r;

        -- *** Pipe Handling ***
        v.ZeroPipe(1 to v.ZeroPipe'high) := r.ZeroPipe(0 to r.ZeroPipe'high - 1);

        -- *** Zero Detection ***
        -- An input of zero is exact (sin = 0, cos = peak) and its mirrored address wraps to zero,
        -- hence it must not be taken from the table.
        v.ZeroPipe(0) := '0';

        if unsigned(In_Data) = 0 then
            v.ZeroPipe(0) := '1';
        end if;

        -- *** Output Stage ***
        v.Out_Valid := SinValid;
        v.Out_Sin   := SinResult;
        v.Out_Cos   := CosResult;

        if r.ZeroPipe(r.ZeroPipe'high) = '1' then
            v.Out_Sin := Zero_c;
            v.Out_Cos := Peak_c;
        end if;

        -- *** Assign Signal ***
        r_next <= v;
    end process;

    -- *** Sequential Process ***
    p_seq : process (Clk) is
    begin
        if rising_edge(Clk) then
            r <= r_next;

            -- Reset
            if Rst = '1' then
                r.ZeroPipe  <= (others => '0');
                r.Out_Valid <= '0';
            end if;
        end if;
    end process;

    -- *** Outputs ***
    Out_Valid <= r.Out_Valid;
    Out_Sin   <= r.Out_Sin;

    g_cos_out : if CosOutput_g generate
        Out_Cos <= r.Out_Cos;
    end generate;

    g_ncos_out : if not CosOutput_g generate
        Out_Cos <= (others => '0');
    end generate;

    -- *** Component Instantiations ***

    -- Sine calculation
    i_calc_sin : entity work.olo_fix_lin_approx_calc
        generic map (
            InFmt_g     => InFmt_g,
            OutFmt_g    => OutFmt_g,
            OffsFmt_g   => OffsFmt_c,
            GradFmt_g   => GradFmt_c,
            TableSize_g => Points_c,
            Round_g     => Round_g,
            Saturate_g  => Saturate_g
        )
        port map (
            Clk        => Clk,
            Rst        => Rst,
            In_Valid   => In_Valid,
            In_Data    => In_Data,
            Out_Valid  => SinValid,
            Out_Result => SinResult,
            Tbl_Addr   => SinAddr,
            Tbl_Data   => SinData
        );

    -- Cosine calculation - uses the second read port of the table with the mirrored address
    g_cos : if CosOutput_g generate

        -------------------------------------------------------------------------------------------
        -- Table (ROM, second read port)
        -------------------------------------------------------------------------------------------
        p_table_cos : process (Clk) is
        begin
            if rising_edge(Clk) then
                CosData <= Table_v(to_integer(unsigned(CosAddr)));
            end if;
        end process;

        i_calc_cos : entity work.olo_fix_lin_approx_calc
            generic map (
                InFmt_g     => InFmt_g,
                OutFmt_g    => OutFmt_g,
                OffsFmt_g   => OffsFmt_c,
                GradFmt_g   => GradFmt_c,
                TableSize_g => Points_c,
                Round_g     => Round_g,
                Saturate_g  => Saturate_g
            )
            port map (
                Clk        => Clk,
                Rst        => Rst,
                In_Valid   => In_Valid,
                In_Data    => MirrorData,
                Out_Valid  => open,
                Out_Result => CosResult,
                Tbl_Addr   => CosAddr,
                Tbl_Data   => CosData
            );

    end generate;

    g_ncos : if not CosOutput_g generate
        CosAddr   <= (others => '0');
        CosData   <= (others => '0');
        CosResult <= (others => '0');
    end generate;

end architecture;
