---------------------------------------------------------------------------------------------------
-- Copyright (c) 2026 by Oliver Bründler
-- Authors: Oliver Bruendler
---------------------------------------------------------------------------------------------------

---------------------------------------------------------------------------------------------------
-- Description
---------------------------------------------------------------------------------------------------
-- This entity implements the calculation part of a linear approximation of an arbitrary function.
-- The function values (offset) and their derivatives (gradient) are stored in a table which is
-- attached externally. The table normally is generated by the Python code generator
-- olo_fix_lin_approx, which also generates a wrapper entity containing the table.
--
-- Documentation:
-- https://github.com/open-logic/open-logic/blob/main/doc/fix/olo_fix_lin_approx_calc.md
--
-- Note: The link points to the documentation of the latest release. If you
--       use an older version, the documentation might not match the code.

---------------------------------------------------------------------------------------------------
-- Package
---------------------------------------------------------------------------------------------------
package olo_fix_lin_approx_pkg is

    -- Latency of olo_fix_lin_approx_calc in clock cycles for a given TableLatency_g. Entities and
    -- testbenches depending on the latency use this function, hence it is the only place to update
    -- when the pipeline changes.
    function linApproxLatency (TableLatency : positive) return positive;

end package;

package body olo_fix_lin_approx_pkg is

    function linApproxLatency (TableLatency : positive) return positive is
    begin
        return 7 + TableLatency;
    end function;

end package body;

---------------------------------------------------------------------------------------------------
-- Libraries
---------------------------------------------------------------------------------------------------
library ieee;
    use ieee.std_logic_1164.all;
    use ieee.numeric_std.all;
    use ieee.math_real.all;

library work;
    use work.olo_base_pkg_math.all;
    use work.olo_base_pkg_string.all;
    use work.en_cl_fix_pkg.all;
    use work.olo_fix_pkg.all;
    use work.olo_fix_lin_approx_pkg.all;

---------------------------------------------------------------------------------------------------
-- Entity Declaration
---------------------------------------------------------------------------------------------------

entity olo_fix_lin_approx_calc is
    generic (
        -- Formats (defined by the table, do not modify without regenerating the table)
        InFmt_g        : string;
        OutFmt_g       : string;
        OffsFmt_g      : string;
        GradFmt_g      : string;
        TableSize_g    : positive;
        -- Table read latency in clock cycles (increase for better timing of slow ROMs)
        TableLatency_g : positive range 1 to 3 := 1;
        -- Round / Saturate
        Round_g        : string                := FixRound_NonSymPos_c;
        Saturate_g     : string                := FixSaturate_Sat_c
    );
    port (
        -- Control Ports
        Clk        : in    std_logic;
        Rst        : in    std_logic;
        -- Input
        In_Valid   : in    std_logic := '1';
        In_Data    : in    std_logic_vector(fixFmtWidthFromString(InFmt_g) - 1 downto 0);
        -- Output
        Out_Valid  : out   std_logic;
        Out_Result : out   std_logic_vector(fixFmtWidthFromString(OutFmt_g) - 1 downto 0);
        -- Table Interface
        Tbl_Addr   : out   std_logic_vector(log2ceil(TableSize_g) - 1 downto 0);
        Tbl_Data   : in    std_logic_vector(fixFmtWidthFromString(OffsFmt_g) + fixFmtWidthFromString(GradFmt_g) - 1 downto 0)
    );
end entity;

architecture rtl of olo_fix_lin_approx_calc is

    -- Constants
    constant EntityName_c : string      := "olo_fix_lin_approx_calc";
    constant InFmt_c      : FixFormat_t := cl_fix_format_from_string(InFmt_g);
    constant OffsFmt_c    : FixFormat_t := cl_fix_format_from_string(OffsFmt_g);
    constant GradFmt_c    : FixFormat_t := cl_fix_format_from_string(GradFmt_g);

    -- Derived Formats
    constant IndexBits_c    : natural := log2ceil(TableSize_g);
    constant OffsetBits_c   : natural := cl_fix_width(InFmt_c) - IndexBits_c;
    -- Remainder relative to the beginning of the segment (unsigned)
    constant RemFmt_c       : FixFormat_t := (0, OffsetBits_c - InFmt_c.F, InFmt_c.F);
    -- Remainder relative to the center of the segment (signed, MSB inverted)
    constant RemFmtSigned_c : FixFormat_t := (1, RemFmt_c.I - 1, RemFmt_c.F);
    -- Table index (unsigned, negative inputs wrap into the upper half of the table)
    -- The index is the input shifted right by the number of remainder bits, hence F = -RemFmt_c.I
    constant IdxFmt_c       : FixFormat_t := (0, InFmt_c.S + InFmt_c.I, -RemFmt_c.I);
    -- Intermediate results (lossless, hence no rounding/saturation is required)
    constant MulFmt_c       : FixFormat_t := cl_fix_mult_fmt(GradFmt_c, RemFmtSigned_c);
    constant AddFmt_c       : FixFormat_t := cl_fix_add_fmt(OffsFmt_c, MulFmt_c);

    -- Pipeline stages depending on the table read latency
    constant TblStg_c : positive := 2 + TableLatency_g; -- Register table outputs
    constant MulStg_c : positive := TblStg_c + 1;       -- Multiplication
    constant AddStg_c : positive := TblStg_c + 2;       -- Addition

    -- Table data ranges
    subtype OffsRng_c is natural range cl_fix_width(OffsFmt_c) - 1 downto 0;
    subtype GradRng_c is natural range cl_fix_width(GradFmt_c) + OffsRng_c'high downto
                                       OffsRng_c'high + 1;

    -- Types
    type Rem_t is array (natural range <>) of std_logic_vector(cl_fix_width(RemFmt_c) - 1 downto 0);
    type Offs_t is array (natural range <>) of std_logic_vector(cl_fix_width(OffsFmt_c) - 1 downto 0);

    -- Two Process Method
    -- The offset is delayed by one stage to arrive at the adder together with the product.
    -- Note: When changing the number of stages, update olo_fix_lin_approx_pkg.linApproxLatency().
    type TwoProcess_r is record
        Valid    : std_logic_vector(0 to AddStg_c);
        In_0     : std_logic_vector(In_Data'range);
        TblIdx_1 : std_logic_vector(cl_fix_width(IdxFmt_c) - 1 downto 0);
        Remain   : Rem_t(1 to TblStg_c);
        Grad     : std_logic_vector(cl_fix_width(GradFmt_c) - 1 downto 0);
        Offs     : Offs_t(TblStg_c to MulStg_c);
        MulVal   : std_logic_vector(cl_fix_width(MulFmt_c) - 1 downto 0);
        AddVal   : std_logic_vector(cl_fix_width(AddFmt_c) - 1 downto 0);
    end record;

    signal r, r_next : TwoProcess_r;

begin

    -- *** Assertions ***
    -- synthesis translate_off
    assert isPower2(TableSize_g)
        report errorMessage(EntityName_c, "TableSize_g must be a power of two")
        severity error;
    assert IndexBits_c < cl_fix_width(InFmt_c)
        report errorMessage(EntityName_c, "TableSize_g must be smaller than 2**width(InFmt_g)")
        severity error;
    assert linApproxLatency(TableLatency_g) = AddStg_c + 3
        report errorMessage(EntityName_c, "Internal error: linApproxLatency() does not match the pipeline")
        severity failure;
    -- synthesis translate_on

    -- *** Combinatorial Process ***
    p_comb : process (all) is
        variable v : TwoProcess_r;
    begin
        -- *** Hold variables stable ***
        v := r;

        -- *** Pipe Handling ***
        v.Valid(1 to v.Valid'high)   := r.Valid(0 to r.Valid'high - 1);
        v.Remain(2 to v.Remain'high) := r.Remain(1 to r.Remain'high - 1);
        v.Offs(MulStg_c)             := r.Offs(TblStg_c);

        -- *** Stage 0 - Input Register ***
        v.Valid(0) := In_Valid;
        v.In_0     := In_Data;

        -- *** Stage 1 - Split Input into Index and Remainder ***
        v.TblIdx_1  := cl_fix_resize(r.In_0, InFmt_c, IdxFmt_c, Trunc_s, None_s);
        v.Remain(1) := cl_fix_resize(r.In_0, InFmt_c, RemFmt_c, Trunc_s, None_s);
        -- Invert MSB to get an offset relative to the center of the segment (signed)
        v.Remain(1)(v.Remain(1)'high) := not v.Remain(1)(v.Remain(1)'high);

        -- *** Stages 2 to TblStg_c-1 - Reserved for Table Read Latency ***

        -- *** Stage TblStg_c - Register Table Outputs ***
        v.Offs(TblStg_c) := Tbl_Data(OffsRng_c);
        v.Grad           := Tbl_Data(GradRng_c);

        -- *** Stage MulStg_c - Multiplication ***
        -- Both multiplier inputs are registered (r.Grad and r.Remain(TblStg_c)) to allow the
        -- multiplication to be mapped into a DSP slice including its input registers.
        -- The remainder is reinterpreted as signed (its MSB was inverted in stage 1)
        v.MulVal := cl_fix_mult(r.Grad, GradFmt_c,
                                r.Remain(TblStg_c), RemFmtSigned_c,
                                MulFmt_c, Trunc_s, None_s);

        -- *** Stage AddStg_c - Addition ***
        -- Executed at full precision and without round/saturate to fit into a DSP slice
        v.AddVal := cl_fix_add(r.Offs(MulStg_c), OffsFmt_c,
                               r.MulVal, MulFmt_c,
                               AddFmt_c, Trunc_s, None_s);

        -- *** Assign Signal ***
        r_next <= v;
    end process;

    -- *** Sequential Process ***
    p_seq : process (Clk) is
    begin
        if rising_edge(Clk) then
            r <= r_next;

            -- Reset
            if Rst = '1' then
                r.Valid <= (others => '0');
            end if;
        end if;
    end process;

    -- *** Outputs ***
    Tbl_Addr <= r.TblIdx_1;

    -- *** Component Instantiations ***

    -- Output rounding and saturation
    i_resize : entity work.olo_fix_resize
        generic map (
            AFmt_g      => to_string(AddFmt_c),
            ResultFmt_g => OutFmt_g,
            Round_g     => Round_g,
            Saturate_g  => Saturate_g,
            RoundReg_g  => "YES",
            SatReg_g    => "YES"
        )
        port map (
            Clk        => Clk,
            Rst        => Rst,
            In_Valid   => r.Valid(AddStg_c),
            In_A       => r.AddVal,
            Out_Valid  => Out_Valid,
            Out_Result => Out_Result
        );

end architecture;
