---------------------------------------------------------------------------------------------------
-- Copyright (c) 2026 by Oliver Bründler
-- All rights reserved.
-- Authors: Oliver Bruendler
---------------------------------------------------------------------------------------------------

---------------------------------------------------------------------------------------------------
-- Description
---------------------------------------------------------------------------------------------------
-- This entity approximates the sine of one quadrant.
-- The tables are optimized for every supported output format and they are contained in
-- olo_fix_private_lin_approx_qsin_pkg, which is generated by the Python model.
--
-- Use olo_fix_sin to calculate sine and cosine over all four quadrants.
--
-- Documentation:
-- https://github.com/open-logic/open-logic/blob/main/doc/fix/olo_fix_lin_approx_qsin.md
--
-- Note: The link points to the documentation of the latest release. If you
--       use an older version, the documentation might not match the code.

---------------------------------------------------------------------------------------------------
-- Libraries
---------------------------------------------------------------------------------------------------
library ieee;
    use ieee.std_logic_1164.all;
    use ieee.numeric_std.all;

library work;
    use work.olo_base_pkg_math.all;
    use work.olo_base_pkg_string.all;
    use work.olo_base_pkg_attribute.all;
    use work.en_cl_fix_pkg.all;
    use work.olo_fix_pkg.all;
    use work.olo_fix_private_lin_approx_qsin_pkg.all;

---------------------------------------------------------------------------------------------------
-- Entity Declaration
---------------------------------------------------------------------------------------------------

entity olo_fix_lin_approx_qsin is
    generic (
        -- Formats
        OutFmt_g   : string;
        InFmt_g    : string;
        -- Configuration
        UsePortB_g : boolean := false;
        MemStyle_g : string  := "auto";
        -- Round / Saturate
        Round_g    : string  := FixRound_NonSymPos_c;
        Saturate_g : string  := FixSaturate_Sat_c
    );
    port (
        -- Control Ports
        Clk       : in    std_logic;
        Rst       : in    std_logic;
        -- Input
        In_Valid  : in    std_logic                                                     := '1';
        In_A      : in    std_logic_vector(fixFmtWidthFromString(InFmt_g) - 1 downto 0);
        In_B      : in    std_logic_vector(fixFmtWidthFromString(InFmt_g) - 1 downto 0) := (others => '0');
        -- Output
        Out_Valid : out   std_logic;
        Out_A     : out   std_logic_vector(fixFmtWidthFromString(OutFmt_g) - 1 downto 0);
        Out_B     : out   std_logic_vector(fixFmtWidthFromString(OutFmt_g) - 1 downto 0)
    );
end entity;

architecture rtl of olo_fix_lin_approx_qsin is

    -- Constants
    constant EntityName_c : string      := "olo_fix_lin_approx_qsin";
    constant InFmt_c      : FixFormat_t := cl_fix_format_from_string(InFmt_g);
    constant OutFmt_c     : FixFormat_t := cl_fix_format_from_string(OutFmt_g);

    -- Table configuration. The table is selected by name from the generated package - the same name
    -- is assembled by the Python model (see qsin_table_name()).
    constant TableName_c : string := "qsin_i" & integer'image(OutFmt_c.I) &
                                     "f" & integer'image(OutFmt_c.F);

    constant TableFull_c : LinApproxTable_t := getTable(TableName_c);
    constant Points_c    : positive         := getTableSize(TableName_c);
    constant OffsFmt_c   : string           := getOffsetFmt(TableName_c);
    constant GradFmt_c   : string           := getGradientFmt(TableName_c);
    constant TblWidth_c  : positive         := fixFmtWidthFromString(OffsFmt_c) +
                                               fixFmtWidthFromString(GradFmt_c);

    -- Table types
    subtype TblEntry_t is std_logic_vector(TblWidth_c - 1 downto 0);
    type Tbl_t is array (0 to Points_c - 1) of TblEntry_t;

    -- Strip the padding the generated package uses to give all tables the same entry width
    function tableContent return Tbl_t is
        variable Tbl_v : Tbl_t;
    begin

        for i in Tbl_v'range loop
            Tbl_v(i) := TableFull_c(i)(TblWidth_c - 1 downto 0);
        end loop;

        return Tbl_v;
    end function;

    -- Table content - each entry contains the gradient (MSBs) and the offset (LSBs)
    -- Implemented as shared variable because attributes do not apply properly to constants
    shared variable Table_v : Tbl_t := tableContent;

    -- Synthesis attributes - control ROM style
    attribute rom_style of Table_v    : variable is MemStyle_g;
    attribute romstyle of Table_v     : variable is MemStyle_g;
    attribute syn_romstyle of Table_v : variable is MemStyle_g;

    -- Signals
    signal AddrA : std_logic_vector(log2ceil(Points_c) - 1 downto 0);
    signal DataA : TblEntry_t;
    signal AddrB : std_logic_vector(log2ceil(Points_c) - 1 downto 0);
    signal DataB : TblEntry_t;

begin

    -- *** Assertions ***
    -- synthesis translate_off
    assert OutFmt_c.S = 1
        report errorMessage(EntityName_c, "OutFmt_g must be signed")
        severity error;
    assert InFmt_c.S = 0 and InFmt_c.I = -2
        report errorMessage(EntityName_c, "InFmt_g must be (0, -2, N) - the quarter phase covers " &
               "one quadrant only, i.e. the range [0, 0.25) in rotations")
        severity error;
    assert cl_fix_width(InFmt_c) > log2ceil(Points_c)
        report errorMessage(EntityName_c, "InFmt_g must be wider than the table has index bits")
        severity error;
    -- synthesis translate_on

    -- *** Table (ROM, one cycle read latency) ***
    p_table_a : process (Clk) is
    begin
        if rising_edge(Clk) then
            DataA <= Table_v(to_integer(unsigned(AddrA)));
            if UsePortB_g then
                DataB <= Table_v(to_integer(unsigned(AddrB)));
            end if;
        end if;
    end process;

    -- *** Component Instantiations ***

    -- Port A calculation
    i_calc_a : entity work.olo_fix_lin_approx_calc
        generic map (
            InFmt_g     => InFmt_g,
            OutFmt_g    => OutFmt_g,
            OffsFmt_g   => OffsFmt_c,
            GradFmt_g   => GradFmt_c,
            TableSize_g => Points_c,
            Round_g     => Round_g,
            Saturate_g  => Saturate_g
        )
        port map (
            Clk        => Clk,
            Rst        => Rst,
            In_Valid   => In_Valid,
            In_Data    => In_A,
            Out_Valid  => Out_Valid,
            Out_Result => Out_A,
            Tbl_Addr   => AddrA,
            Tbl_Data   => DataA
        );

    -- Port B calculation - uses the second read port of the same table
    g_port_b : if UsePortB_g generate

        i_calc_b : entity work.olo_fix_lin_approx_calc
            generic map (
                InFmt_g     => InFmt_g,
                OutFmt_g    => OutFmt_g,
                OffsFmt_g   => OffsFmt_c,
                GradFmt_g   => GradFmt_c,
                TableSize_g => Points_c,
                Round_g     => Round_g,
                Saturate_g  => Saturate_g
            )
            port map (
                Clk        => Clk,
                Rst        => Rst,
                In_Valid   => In_Valid,
                In_Data    => In_B,
                Out_Valid  => open,
                Out_Result => Out_B,
                Tbl_Addr   => AddrB,
                Tbl_Data   => DataB
            );

    end generate;

end architecture;
