---------------------------------------------------------------------------------------------------
-- Copyright (c) 2026 by Oliver Bründler
-- All rights reserved.
-- Authors: Oliver Bruendler
--
-- Based on psi_fix_lin_approx_inv18b from the PSI psi_fix library
-- Copyright (c) 2018 by Paul Scherrer Institute, Switzerland
-- All rights reserved.
---------------------------------------------------------------------------------------------------

---------------------------------------------------------------------------------------------------
-- Description
---------------------------------------------------------------------------------------------------
-- This entity approximates 1/x for x in the range [1, 2). It is meant for internal use only (it is
-- instantiated by olo_fix_inv, which adds the normalization) and hence it is not documented
-- separately. Users shall use olo_fix_inv.
--
-- The leading one of x is implicit, hence the input is the mantissa fraction m in the range [0, 1)
-- and the function approximated is 1/(1+m), which covers the range (0.5, 1.0].
--
-- The tables are contained in olo_fix_private_lin_approx_inv_pkg, which is generated by the Python
-- model. They are not calculated in VHDL, because the accuracy of ieee.math_real is implementation
-- defined and the table content would therefore differ between tools - which would break the
-- bit-trueness against the Python model. The table configurations (number of points, offset format,
-- gradient format) live in the INV_TABLES dictionary of the Python model. To analyze one precision
-- or to regenerate the package after changing INV_TABLES, run from <root>/src/fix/python:
--   python3 -m olo_fix.olo_fix_private_lin_approx_inv --analyze 18
--   python3 -m olo_fix.olo_fix_private_lin_approx_inv --generate
--
-- Documentation:
-- None

---------------------------------------------------------------------------------------------------
-- Libraries
---------------------------------------------------------------------------------------------------
library ieee;
    use ieee.std_logic_1164.all;
    use ieee.numeric_std.all;

library work;
    use work.olo_base_pkg_math.all;
    use work.olo_base_pkg_string.all;
    use work.olo_base_pkg_attribute.all;
    use work.en_cl_fix_pkg.all;
    use work.olo_fix_pkg.all;
    use work.olo_fix_private_lin_approx_inv_pkg.all;

---------------------------------------------------------------------------------------------------
-- Entity Declaration
---------------------------------------------------------------------------------------------------

entity olo_fix_private_lin_approx_inv is
    generic (
        -- Formats
        OutFmt_g   : string;
        InFmt_g    : string;
        -- Configuration
        MemStyle_g : string := "auto";
        -- Round / Saturate
        Round_g    : string := FixRound_NonSymPos_c;
        Saturate_g : string := FixSaturate_Sat_c
    );
    port (
        -- Control Ports
        Clk       : in    std_logic;
        Rst       : in    std_logic;
        -- Input
        In_Valid  : in    std_logic := '1';
        In_Data   : in    std_logic_vector(fixFmtWidthFromString(InFmt_g) - 1 downto 0);
        -- Output
        Out_Valid : out   std_logic;
        Out_Data  : out   std_logic_vector(fixFmtWidthFromString(OutFmt_g) - 1 downto 0)
    );
end entity;

architecture rtl of olo_fix_private_lin_approx_inv is

    -- Constants
    constant EntityName_c : string      := "olo_fix_private_lin_approx_inv";
    constant InFmt_c      : FixFormat_t := cl_fix_format_from_string(InFmt_g);
    constant OutFmt_c     : FixFormat_t := cl_fix_format_from_string(OutFmt_g);

    -- Supported precisions - one approximation table exists per precision. The list is the same as
    -- the one in the INV_TABLES dictionary of the Python model.
    constant FmtSupported_c : boolean := OutFmt_c.S = 0 and OutFmt_c.I = 1 and
                                         (OutFmt_c.F = 10 or OutFmt_c.F = 14 or
                                          OutFmt_c.F = 18 or OutFmt_c.F = 20);

    -- Table configuration. The table is selected by name from the generated package - the same name
    -- is assembled by the Python model (see inv_table_name()). For unsupported formats an arbitrary
    -- valid table is selected, because the lookup in the package aborts elaboration - which happens
    -- before any assertion is executed and would therefore hide the assertions below (and the ones
    -- in olo_fix_inv) behind a much less specific message.
    constant TableName_c : string := choose(FmtSupported_c,
                                            "inv_f" & integer'image(OutFmt_c.F),
                                            "inv_f10");

    constant TableFull_c : LinApproxTable_t := getTable(TableName_c);
    constant Points_c    : positive         := getTableSize(TableName_c);
    constant OffsFmt_c   : string           := getOffsetFmt(TableName_c);
    constant GradFmt_c   : string           := getGradientFmt(TableName_c);
    constant TblWidth_c  : positive         := fixFmtWidthFromString(OffsFmt_c) +
                                               fixFmtWidthFromString(GradFmt_c);

    -- Table types
    subtype TblEntry_t is std_logic_vector(TblWidth_c - 1 downto 0);
    type Tbl_t is array (0 to Points_c - 1) of TblEntry_t;

    -- Strip the padding the generated package uses to give all tables the same entry width
    function tableContent return Tbl_t is
        variable Tbl_v : Tbl_t;
    begin

        for i in Tbl_v'range loop
            Tbl_v(i) := TableFull_c(i)(TblWidth_c - 1 downto 0);
        end loop;

        return Tbl_v;
    end function;

    -- Table content - each entry contains the gradient (MSBs) and the offset (LSBs)
    -- Implemented as shared variable because attributes do not apply properly to constants
    shared variable Table_v : Tbl_t := tableContent;

    -- Synthesis attributes - control ROM style
    attribute rom_style of Table_v    : variable is MemStyle_g;
    attribute romstyle of Table_v     : variable is MemStyle_g;
    attribute syn_romstyle of Table_v : variable is MemStyle_g;

    -- Signals
    signal Addr : std_logic_vector(log2ceil(Points_c) - 1 downto 0);
    signal Data : TblEntry_t;

begin

    -- *** Assertions ***
    -- synthesis translate_off
    assert FmtSupported_c
        report errorMessage(EntityName_c, "OutFmt_g must be (0, 1, P) with P being 10, 14, 18 " &
               "or 20, got " & to_string(OutFmt_c))
        severity error;
    assert InFmt_c.S = 0 and InFmt_c.I = 0
        report errorMessage(EntityName_c, "InFmt_g must be (0, 0, N) - the mantissa fraction " &
               "covers the range [0, 1)")
        severity error;
    assert cl_fix_width(InFmt_c) > log2ceil(Points_c)
        report errorMessage(EntityName_c, "InFmt_g must be wider than the table has index bits")
        severity error;
    -- synthesis translate_on

    -- *** Table (ROM, one cycle read latency) ***
    p_table : process (Clk) is
    begin
        if rising_edge(Clk) then
            Data <= Table_v(to_integer(unsigned(Addr)));
        end if;
    end process;

    -- *** Component Instantiations ***

    -- Approximation calculation
    i_calc : entity work.olo_fix_lin_approx_calc
        generic map (
            InFmt_g     => InFmt_g,
            OutFmt_g    => OutFmt_g,
            OffsFmt_g   => OffsFmt_c,
            GradFmt_g   => GradFmt_c,
            TableSize_g => Points_c,
            Round_g     => Round_g,
            Saturate_g  => Saturate_g
        )
        port map (
            Clk        => Clk,
            Rst        => Rst,
            In_Valid   => In_Valid,
            In_Data    => In_Data,
            Out_Valid  => Out_Valid,
            Out_Result => Out_Data,
            Tbl_Addr   => Addr,
            Tbl_Data   => Data
        );

end architecture;
