---------------------------------------------------------------------------------------------------
-- Copyright (c) 2026 by Oliver Bründler
-- All rights reserved.
-- Authors: Oliver Bruendler
---------------------------------------------------------------------------------------------------

---------------------------------------------------------------------------------------------------
-- Description
---------------------------------------------------------------------------------------------------
-- This entity implements the calculation part of a linear approximation of an arbitrary function.
-- The function values (offset) and their derivatives (gradient) are stored in a table which is
-- attached externally. The table normally is generated by the Python code generator
-- olo_fix_lin_approx, which also generates a wrapper entity containing the table.
--
-- Documentation:
-- https://github.com/open-logic/open-logic/blob/main/doc/fix/olo_fix_lin_approx_calc.md
--
-- Note: The link points to the documentation of the latest release. If you
--       use an older version, the documentation might not match the code.

---------------------------------------------------------------------------------------------------
-- Libraries
---------------------------------------------------------------------------------------------------
library ieee;
    use ieee.std_logic_1164.all;
    use ieee.numeric_std.all;
    use ieee.math_real.all;

library work;
    use work.olo_base_pkg_math.all;
    use work.olo_base_pkg_string.all;
    use work.en_cl_fix_pkg.all;
    use work.olo_fix_pkg.all;

---------------------------------------------------------------------------------------------------
-- Entity Declaration
---------------------------------------------------------------------------------------------------

entity olo_fix_lin_approx_calc is
    generic (
        -- Formats (defined by the table, do not modify without regenerating the table)
        InFmt_g     : string;
        OutFmt_g    : string;
        OffsFmt_g   : string;
        GradFmt_g   : string;
        TableSize_g : positive;
        -- Round / Saturate
        Round_g     : string := FixRound_NonSymPos_c;
        Saturate_g  : string := FixSaturate_Sat_c
    );
    port (
        -- Control Ports
        Clk        : in    std_logic;
        Rst        : in    std_logic;
        -- Input
        In_Valid   : in    std_logic := '1';
        In_Data    : in    std_logic_vector(fixFmtWidthFromString(InFmt_g) - 1 downto 0);
        -- Output
        Out_Valid  : out   std_logic;
        Out_Result : out   std_logic_vector(fixFmtWidthFromString(OutFmt_g) - 1 downto 0);
        -- Table Interface
        Tbl_Addr   : out   std_logic_vector(log2ceil(TableSize_g) - 1 downto 0);
        Tbl_Data   : in    std_logic_vector(fixFmtWidthFromString(OffsFmt_g) + fixFmtWidthFromString(GradFmt_g) - 1 downto 0)
    );
end entity;

architecture rtl of olo_fix_lin_approx_calc is

    -- Constants
    constant EntityName_c : string      := "olo_fix_lin_approx_calc";
    constant InFmt_c      : FixFormat_t := cl_fix_format_from_string(InFmt_g);
    constant OutFmt_c     : FixFormat_t := cl_fix_format_from_string(OutFmt_g);
    constant OffsFmt_c    : FixFormat_t := cl_fix_format_from_string(OffsFmt_g);
    constant GradFmt_c    : FixFormat_t := cl_fix_format_from_string(GradFmt_g);

    -- Derived Formats
    constant IndexBits_c    : natural := log2ceil(TableSize_g);
    constant OffsetBits_c   : natural := cl_fix_width(InFmt_c) - IndexBits_c;
    -- Remainder relative to the beginning of the segment (unsigned)
    constant RemFmt_c       : FixFormat_t := (0, OffsetBits_c - InFmt_c.F, InFmt_c.F);
    -- Remainder relative to the center of the segment (signed, MSB inverted)
    constant RemFmtSigned_c : FixFormat_t := (1, RemFmt_c.I - 1, RemFmt_c.F);
    -- Table index (unsigned, negative inputs wrap into the upper half of the table)
    -- The index is the input shifted right by the number of remainder bits, hence F = -RemFmt_c.I
    constant IdxFmt_c       : FixFormat_t := (0, InFmt_c.S + InFmt_c.I, -RemFmt_c.I);
    -- Intermediate results (lossless, hence no rounding/saturation is required)
    constant MulFmt_c       : FixFormat_t := cl_fix_mult_fmt(GradFmt_c, RemFmtSigned_c);
    constant AddFmt_c       : FixFormat_t := cl_fix_add_fmt(OffsFmt_c, MulFmt_c);

    -- Table data ranges
    subtype OffsRng_c is natural range cl_fix_width(OffsFmt_c) - 1 downto 0;
    subtype GradRng_c is natural range cl_fix_width(GradFmt_c) + OffsRng_c'high downto
                                       OffsRng_c'high + 1;

    -- Types
    type Rem_t is array (natural range <>) of std_logic_vector(cl_fix_width(RemFmt_c) - 1 downto 0);
    type Offs_t is array (natural range <>) of std_logic_vector(cl_fix_width(OffsFmt_c) - 1 downto 0);

    -- Two Process Method
    -- The offset is delayed by one stage to arrive at the adder together with the product.
    type TwoProcess_r is record
        Valid    : std_logic_vector(0 to 5);
        In_0     : std_logic_vector(In_Data'range);
        TblIdx_1 : std_logic_vector(cl_fix_width(IdxFmt_c) - 1 downto 0);
        Remain   : Rem_t(1 to 3);
        Grad_3   : std_logic_vector(cl_fix_width(GradFmt_c) - 1 downto 0);
        Offs     : Offs_t(3 to 4);
        MulVal_4 : std_logic_vector(cl_fix_width(MulFmt_c) - 1 downto 0);
        Add_5    : std_logic_vector(cl_fix_width(AddFmt_c) - 1 downto 0);
    end record;

    signal r, r_next : TwoProcess_r;

begin

    -- *** Assertions ***
    -- synthesis translate_off
    assert isPower2(TableSize_g)
        report errorMessage(EntityName_c, "TableSize_g must be a power of two")
        severity error;
    assert IndexBits_c < cl_fix_width(InFmt_c)
        report errorMessage(EntityName_c, "TableSize_g must be smaller than 2**width(InFmt_g)")
        severity error;
    -- synthesis translate_on

    -- *** Combinatorial Process ***
    p_comb : process (all) is
        variable v : TwoProcess_r;
    begin
        -- *** Hold variables stable ***
        v := r;

        -- *** Pipe Handling ***
        v.Valid(1 to v.Valid'high)   := r.Valid(0 to r.Valid'high - 1);
        v.Remain(2 to v.Remain'high) := r.Remain(1 to r.Remain'high - 1);
        v.Offs(4 to v.Offs'high)     := r.Offs(3 to r.Offs'high - 1);

        -- *** Stage 0 - Input Register ***
        v.Valid(0) := In_Valid;
        v.In_0     := In_Data;

        -- *** Stage 1 - Split Input into Index and Remainder ***
        v.TblIdx_1  := cl_fix_resize(r.In_0, InFmt_c, IdxFmt_c, Trunc_s, None_s);
        v.Remain(1) := cl_fix_resize(r.In_0, InFmt_c, RemFmt_c, Trunc_s, None_s);
        -- Invert MSB to get an offset relative to the center of the segment (signed)
        v.Remain(1)(v.Remain(1)'high) := not v.Remain(1)(v.Remain(1)'high);

        -- *** Stage 2 - Reserved for Table Read Latency ***

        -- *** Stage 3 - Register Table Outputs ***
        v.Offs(3) := Tbl_Data(OffsRng_c);
        v.Grad_3  := Tbl_Data(GradRng_c);

        -- *** Stage 4 - Multiplication ***
        -- Both multiplier inputs are registered (r.Grad_3 and r.Remain(3)) to allow the
        -- multiplication to be mapped into a DSP slice including its input registers.
        -- The remainder is reinterpreted as signed (its MSB was inverted in stage 1)
        v.MulVal_4 := cl_fix_mult(r.Grad_3, GradFmt_c,
                                  r.Remain(3), RemFmtSigned_c,
                                  MulFmt_c, Trunc_s, None_s);

        -- *** Stage 5 - Addition ***
        -- Executed at full precision and without round/saturate to fit into a DSP slice
        v.Add_5 := cl_fix_add(r.Offs(4), OffsFmt_c,
                              r.MulVal_4, MulFmt_c,
                              AddFmt_c, Trunc_s, None_s);

        -- *** Assign Signal ***
        r_next <= v;
    end process;

    -- *** Sequential Process ***
    p_seq : process (Clk) is
    begin
        if rising_edge(Clk) then
            r <= r_next;

            -- Reset
            if Rst = '1' then
                r.Valid <= (others => '0');
            end if;
        end if;
    end process;

    -- *** Outputs ***
    Tbl_Addr <= r.TblIdx_1;

    -- *** Component Instantiations ***

    -- Output rounding and saturation
    i_resize : entity work.olo_fix_resize
        generic map (
            AFmt_g      => to_string(AddFmt_c),
            ResultFmt_g => OutFmt_g,
            Round_g     => Round_g,
            Saturate_g  => Saturate_g,
            RoundReg_g  => "YES",
            SatReg_g    => "YES"
        )
        port map (
            Clk        => Clk,
            Rst        => Rst,
            In_Valid   => r.Valid(5),
            In_A       => r.Add_5,
            Out_Valid  => Out_Valid,
            Out_Result => Out_Result
        );

end architecture;
