name: Setup Environment Action
description: 'Setup the environment for any Open Logic jobs'

inputs:
  os:
    description: 'The runner OS'
    required: true

runs:
  using: 'composite'
  steps:
    #Python Setup
    - name: Setup python
      uses: actions/setup-python@v5
      with: 
        python-version: '3.10'
        cache: 'pip'
    - name: Install Python Requiremetns
      shell: bash
      run: pip install -r ./.github/workflows/requirements.txt
    #Setup APT Get packages
    - name: Setup apt packages
      uses: actions/cache@v3
      with:
        path: |
          /var/cache/apt
          /var/lib/apt/lists
        key: ${{ runner.os }}-apt-cache-${{ hashFiles('path/to/dependency-list.txt') }}
        restore-keys: |
          ${{ runner.os }}-apt-cache-
    - name: Install APT packages
      run: |
        sudo apt-get update
        sudo apt-get install -y gnat libgnat-9
    #Setup GHDL
    - name: Set up GHDL cache
      id: cache-ghdl
      uses: actions/cache@v3
      with:
        path: ~/ghdl
        key: ${{ runner.os }}-ghdl-${{ hashFiles('~/ghdl-gha-ubuntu-20.04-mcode.tgz') }}
        restore-keys: |
          ${{ runner.os }}-ghdl-
    - name: Download and extract GHDL if not cached
      if: steps.cache-ghdl.outputs.cache-hit != 'true'
      run: |
        mkdir -p ~/ghdl
        wget https://github.com/ghdl/ghdl/releases/download/v3.0.0/ghdl-gha-ubuntu-20.04-mcode.tgz
        tar zxvf ghdl-gha-ubuntu-20.04-mcode.tgz -C ~/ghdl
    - name: Add GHDL to PATH
      run: echo "$HOME/ghdl/bin" >> $GITHUB_PATH