name: Setup Environment Action
description: 'Setup the environment for any Open Logic jobs'

inputs:
  os:
    description: 'The runner OS'
    required: true

runs:
  using: 'composite'
  steps:
    #Python Setup
    - name: Setup python
      uses: actions/setup-python@v5
      with: 
        python-version: '3.10'
        cache: 'pip'
    - name: Install Python Requiremetns
      shell: bash
      run: pip install -r ./.github/workflows/requirements.txt
    #Setup APT Get packages
    - name: Setup APT packages cache directory
      uses: actions/cache@v3
      with:
        path: |
          ${{ github.workspace }}/apt-cache
        key: ${{ runner.os }}-apt-cache-${{ hashFiles('.github/workflows/apt-dependencies.txt') }}
        restore-keys: |
          ${{ runner.os }}-apt-cache-
    - name: Install APT packages
      run: |
        mkdir -p ${{ github.workspace }}/apt-cache
        sudo cp ${{ github.workspace }}/apt-cache/* /var/cache/apt/archives/ || true
        sudo apt-get update
        xargs -a .github/workflows/apt-dependencies.txt sudo apt-get install -y
        sudo cp /var/cache/apt/archives/* ${{ github.workspace }}/apt-cache/ || true
    - name: Change permissions on custom apt cache directory
      run: sudo chmod -R 777 ${{ github.workspace }}/apt-cache
    #Setup GHDL
    - name: Download and extract GHDL
      shell: bash
      run: |
        mkdir -p ~/ghdl
        wget https://github.com/ghdl/ghdl/releases/download/v3.0.0/ghdl-gha-ubuntu-20.04-mcode.tgz
        tar zxvf ghdl-gha-ubuntu-20.04-mcode.tgz -C ~/ghdl
    - name: Add GHDL to PATH
      shell: bash
      run: echo "$HOME/ghdl/bin" >> $GITHUB_PATH