name: Simulation Action
description: 'Run Simulations for Open-Logic'

inputs:
  os:
    description: 'The runner OS'
    required: true
  simulator:
    description: 'ghdl, nvc'
    required: true
  area:
    description: 'Open Logic area to simulate (base, axi, intf, fix, ft)'
    required: true

runs:
  using: 'composite'
  steps:
    #Run Simulation
    - name: Run Simulation
      shell: bash
      run: |
        cd ./sim
        python3 run.py --${{ inputs.simulator }} --minimal "olo_tb.olo_${{ inputs.area }}_*" --xunit-xml sim_report_${{ inputs.simulator }}_${{ inputs.area }}.xml -p 16
    - name: Upload sim results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: simulation-${{ inputs.simulator }}-${{ inputs.area }}-artifacts
        path: sim/sim_report_${{ inputs.simulator }}_${{ inputs.area }}.xml

