name: AWS-TEST
run-name: ${{ github.actor }} triggered AWS-TEST

# Set the permissions for the workflow
permissions:
  checks: write
  pull-requests: write

#Set Triggers
on:
  workflow_dispatch:
  pull_request:
  
#Jobs  
jobs:
  start-instance:
    runs-on: ubuntu-latest
    steps:
      #General Setup
      - name: Checkout actions
        uses: actions/checkout@v4
      #Start AWS Instance
      - name: Start Instance
        uses: ./.github/actions/start-aws-instance
        with:
          instance_id: i-08d60c6d6d93c636b
          region: eu-central-1
          aws_secret_access_key: ${{ secrets.AWS_SECRET }}
          aws_access_key_id: ${{ secrets.AWS_KEY }}

  do-something:
    runs-on: [self-hosted, aws]
    needs: start-instance
    steps:
      # Checkout the repository
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: true
      # Questa Test
      - name: questa test
        if: false
        run: |
          source $LOCAL_TOOLS
          cd ./sim
          python3 run.py --modelsim --coverage
          cd ..   
      # Vivado Test
      - name: vivado test
        if: false
        run: |
          source $LOCAL_TOOLS
          cd ./doc/tutorials/VivadoTutorial/Files
          vivado -mode batch -source scripted_build.tcl
          cd ../../../..
      # Quartus Test
      - name: quartus test
        if: false
        run: |
          source $LOCAL_TOOLS
          cd ./doc/tutorials/QuartusTutorial/Files
          quartus_sh -t scripted_build.tcl
          cd ../../../..
      # Efinity Test
      - name: efinity test
        if: false
        run: |
          source $LOCAL_TOOLS
          cd ./doc/tutorials/EfinityTutorial/Files/prj_vhdl
          efx_run --prj ./prj_vhdl.xml
          cd ../../../../..
      # Gowin
      - name: gowin test
        if: false
        run: |
          source $LOCAL_TOOLS
          cd ./doc/tutorials/GowinTutorial/Files
          gw_sh scripted_build_sh.tcl
          cd ../../../..
      # Libero
      - name: libero test
        if: true
        run: |
          source $LOCAL_TOOLS
          cd ./doc/tutorials/LiberoTutorial/Files
          libero script:scripted_build.tcl
          cd ../../../..

  # Stopping the instance is not required (it stops automatically
  # when it is unused for some time, controlled by AWS alarm)