name: AWS-TEST
run-name: ${{ github.actor }} triggered AWS-TEST

# Set the permissions for the workflow
permissions:
  checks: write
  pull-requests: write

#Set Triggers
on:
  workflow_dispatch:
  pull_request:
  
#Jobs  
jobs:
  start-instance:
    runs-on: ubuntu-latest
    steps:
      #General Setup
      - name: Checkout actions
        uses: actions/checkout@v4
      #Start AWS Instance
      - name: Start Instance
        uses: ./.github/actions/start-aws-instance
        with:
          instance_id: i-08d60c6d6d93c636b
          region: eu-central-1
          aws_secret_access_key: ${{ secrets.AWS_SECRET }}
          aws_access_key_id: ${{ secrets.AWS_KEY }}

  do-something:
    runs-on: [self-hosted, aws]
    needs: start-instance
    steps:
      # Checkout the repository
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: true
      # echo $LOCAL_TOOLS >> $GITHUB_PATH
      # Placeholder
      - name: Do work
        run: |
          source $LOCAL_TOOLS
          ifconfig
          echo "Instance ENV"
          printenv
          cd ./doc/tutorials/VivadoTutorial/Files
          vivado -mode batch -source scripted_build.tcl

  # Stopping the instance is not required (it stops automatically
  # when it is unused for some time, controlled by AWS alarm)