name: DOC-Check
run-name: ${{ github.actor }} triggered DOC Check

# Set the permissions for the workflow
permissions:
  checks: write
  pull-requests: write

#Set Triggers
on:
  push:
  workflow_dispatch:
  pull_request:
  schedule:
    - cron: '0 3 * * 1'

#Jobs
jobs:
  markdown-lint:
    runs-on: ubuntu-latest
    steps:

      #General Setup
      - name: Checkout repo
        uses: actions/checkout@v4
      #Run markdownlint
      - name: Run markdownlint
        uses: DavidAnson/markdownlint-cli2-action@v17
        with:
          globs: '**/*.md'
          config: '.markdownlint.json'
