name: simulation
run-name: ${{ github.actor }} triggered HDL Simlations

# Set the permissions for the workflow
permissions:
  checks: write
  pull-requests: write

#Set Triggers
on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
  schedule:
    - cron: '0 3 * * 1'
  
#Jobs  
jobs:
  simulation-ghdl:
    runs-on: ubuntu-latest
    steps:
      #Run Simulation
      - name: Run Simulation
        uses: ./.github/actions/simulation
        with:
          os: ${{ runner.os }}
          simulator: ghdl

  simulation-nvc:
    runs-on: ubuntu-latest
    steps:
      #Run Simulation
      - name: Run Simulation
        uses: ./.github/actions/simulation
        with:
          os: ${{ runner.os }}
          simulator: nvc
