name: simulation
run-name: ${{ github.actor }} is HDL Simlations
on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
  schedule:
    - cron: '0 3 * * 1'
  
  
jobs:
  simulation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
      - name: Run Simulation
        run: |
         source ./.github/workflows/install_ghdl.sh
         source ./.github/workflows/install_python.sh
         source ./.github/workflows/run_simulation.sh
         echo "Simulation Done"
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: VUnit Tests
          path: sim/sim_report.xml
